.PHONY: clean All

All:
	@echo "----------Building project:[ C++_cals_prj - Debug ]----------"
	@cd "C++_cals_prj" && "$(MAKE)" -f  "C++_cals_prj.mk"
clean:
	@echo "----------Cleaning project:[ C++_cals_prj - Debug ]----------"
	@cd "C++_cals_prj" && "$(MAKE)" -f  "C++_cals_prj.mk" clean
